// <auto-generated />
using System;
using EximStockTransactions.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EximStockTransactions.Infrastructure.Migrations
{
    [DbContext(typeof(EximStockTransactionsDbContext))]
    partial class EximStockTransactionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EximStockTransactions.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OnHandQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LowStockThreshold = 5,
                            Name = "Item A",
                            OnHandQuantity = 0,
                            SKU = "ABC123",
                            UnitPrice = 10.50m
                        },
                        new
                        {
                            Id = 2,
                            LowStockThreshold = 3,
                            Name = "Item B",
                            OnHandQuantity = 0,
                            SKU = "DEF456",
                            UnitPrice = 20.00m
                        });
                });

            modelBuilder.Entity("EximStockTransactions.Domain.Entities.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("StockTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Initial Id 1 stock",
                            ItemId = 1,
                            QuantityChange = 50,
                            Timestamp = new DateTime(2025, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Initial Id 2 Stock",
                            ItemId = 2,
                            QuantityChange = 30,
                            Timestamp = new DateTime(2025, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EximStockTransactions.Domain.Entities.StockTransaction", b =>
                {
                    b.HasOne("EximStockTransactions.Domain.Entities.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("EximStockTransactions.Domain.Entities.Item", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
